#!/bin/bash

# vxcli - A CLI tool for multicloud Services: Deploying applications on various cloud platforms
# CLI installed globally. You can now use 'vxcli' (or 'vx', 'vxcloud') from anywhere!
# test commands
# vxcli deploy --app dockerapp1 --cloud aws --service ec2 --username wesjetty
# vxcli deploy --app websitecloud1 --cloud valtunox --service vm --username wesjetty

# Always run from the project root (where go.mod lives), regardless of
# whether the script was invoked from bin/ or the project root.
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$PROJECT_ROOT" || { echo "Failed to cd to project root"; exit 1; }

echo "Building vxcli..."
echo "  Project root: $PROJECT_ROOT"

# Set GOPATH if not set
if [ -z "$GOPATH" ]; then
    export GOPATH=$HOME/go
fi

# Ensure directories exist
mkdir -p bin

GOOS_DETECTED=$(uname -s 2>/dev/null || echo "Unknown")

# ============================================================================
#  SINGLE SOURCE OF TRUTH:  scripts/   (top-level, edit here)
#  GENERATED COPY:          services/cli/cmd/embedded_scripts/   (DO NOT EDIT)
#
#  Go's //go:embed cannot reach `..` paths, so `services/cli/cmd/install_catalog.go`
#  cannot embed `../../../scripts` directly — it has to embed a sibling dir.
#  This block wipes that sibling dir and re-syncs from scripts/ before every
#  build, guaranteeing the vxcli binary always ships the current scripts/.
#  The sibling dir is gitignored. NEVER hand-edit anything inside it: this
#  script will overwrite it on the next build.
# ============================================================================
EMBED_DST="services/cli/cmd/embedded_scripts"
echo "  ✦ Re-syncing embedded scripts:  scripts/  →  $EMBED_DST"
echo "    (embedded_scripts is auto-generated; edit scripts/ only)"
rm -rf "$EMBED_DST"
mkdir -p "$EMBED_DST"
# Copy scripts/ but skip nothing — Go's `embed` honours all files including
# k8s/ subdirs and YAML manifests, which install_kubernetes_*.sh scripts
# need. We do skip generated session dirs and .git stuff.
cp -r scripts/. "$EMBED_DST/"
find "$EMBED_DST" -type d -name '.git' -prune -exec rm -rf {} + 2>/dev/null || true
find "$EMBED_DST" -type d -name 'node_modules' -prune -exec rm -rf {} + 2>/dev/null || true

# Drop a loud marker so anyone who opens this dir in their editor immediately
# sees the rule. The file is part of the embedded FS but never read by code.
cat > "$EMBED_DST/_AUTO_GENERATED_DO_NOT_EDIT.txt" <<'MARK'
========================================================================
  AUTO-GENERATED — DO NOT EDIT ANYTHING IN THIS DIRECTORY
========================================================================

  This entire directory is wiped and re-created from scripts/ every time
  bin/tenant_build_vxcli.sh runs. Any change you make here is lost on
  the next build.

  EDIT THE SOURCE OF TRUTH INSTEAD:
      ../../../scripts/

  Why this copy exists:
      Go's //go:embed directive (in services/cli/cmd/install_catalog.go)
      cannot reach paths outside its own package directory. So we copy
      scripts/ here at build time so the directive can pick it up.

  Generated by:  bin/tenant_build_vxcli.sh
  Source:        scripts/   (top-level)
========================================================================
MARK

# Build using package path (not file path) so the Go module resolves correctly
go build -o bin/vxcli ./services/cli/

# Check if build was successful
if [ $? -eq 0 ]; then
    echo "Build successful! Binary created at bin/vxcli"
    # Make it executable
    chmod +x bin/vxcli

    # On Linux (Ubuntu/other Linux distros) we can install global symlinks.
    # On non-Linux platforms (macOS/Windows/others) we DO NOT attempt a root-level install.
    case "$GOOS_DETECTED" in
        Linux)
            # Create symlinks for all 3 supported names: vxcli, vx, vxcloud
            for CLI_NAME in vxcli vx vxcloud; do
                TARGET_LINK="/usr/local/bin/$CLI_NAME"
                if command -v sudo >/dev/null 2>&1; then
                    sudo ln -sf "$(pwd)/bin/vxcli" "$TARGET_LINK" 2>/dev/null && echo "Symlink created: $TARGET_LINK" || true
                elif [ -w "/usr/local/bin" ]; then
                    ln -sf "$(pwd)/bin/vxcli" "$TARGET_LINK" 2>/dev/null && echo "Symlink created: $TARGET_LINK" || true
                fi
            done
            echo "CLI installed globally. Use 'vxcli', 'vx', or 'vxcloud' from anywhere!"
            ;;
        *)
            echo "Non-Linux OS detected ($GOOS_DETECTED). Skipping global symlink to avoid writing to root."
            echo "Add $(pwd)/bin to your PATH to use vxcli, e.g.:"
            echo "  export PATH=\"$(pwd)/bin:\$PATH\"  # bash/zsh"
            echo ""
            echo "For convenience, create aliases for vx and vxcloud:"
            echo "  alias vx=vxcli"
            echo "  alias vxcloud=vxcli"
            ;;
    esac
else
    echo "Build failed!"
    exit 1
fi
